# mass of sub (kg)
m: 20.112286
# center of mass
x_m: 0.0
y_m: 0.0
z_m: 0.0
# center of buoyancy
x_b: 0.00491
y_b: 0.00292
z_b: 0.0235
# gravity (m/s^2)
g: 9.81
# density of water (kg/m^3)
rho: 997.0
# buoyancy force (N)
Fb: 273.83
# Fb: 140.479
# moments of inertia (kg m^2)
Ixx: .5209
Iyy: .5205
Izz: .8677
# locations of motors
# max thrust multipliers (if motor is flipped, make f negative)
T_L:
    x: 0.019
    y: -.318
    z: 0.042
    f: 21.4199
T_R:
    x: 0.019
    y: .341
    z: 0.042
    f: 21.4199
T_F:
    x: .349
    y: -0.007
    z: 0.042
    f: 21.4199
T_B:
    x: -.341
    y: 0.001
    z: 0.042
    f: 21.4199
T_FR:
    x: .238
    y: .243
    z: -.012
    f: 21.4199
T_FL:
    x: .242
    y: -.248
    z: -.012
    f: 21.4199
T_BR:
    x: -.238
    y: .244
    z: -.012
    f: 21.4199
T_BL:
    x: -.242
    y: -.245
    z: -.012
    f: 21.4199
# Drag coefficients
Cd_x: 0.296543
Cd_y: 0.296543
Cd_z: 0.406281

# top, bottom, left, right
# intersection of y along x axis
Cd_xT: 0.296543
Cd_xB: 0.296543
# intersection of z along x axis
Cd_xR: 0.296543
Cd_xL: 0.296543

# top, bottom, front, back
# intersectoin of x along y axis
Cd_yT: 0.296543
Cd_yB: 0.296543
# intersectoin of z along y axis
Cd_yF: 0.296543
Cd_yBa: 0.296543

# left, right, front, back
# intersectoin of x along z axis
Cd_zL: 0.406281
Cd_zR: 0.406281
# intersectoin of y along z axis
Cd_zF: 0.406281
Cd_zB: 0.406281

# Surface areas
A_x: .137702228846
A_y: .137702228846
A_z: .265308316645

# top, bottom, left, right
A_xT: .06107
A_xB: .076627
A_xR: .06885
A_xL: .06885

# top, bottom, front, back
A_yT: .06107
A_yB: .076627
A_yF: .06885
A_yBa: .06885

# left, right, front, back
A_zL: .13465
A_zR: .13465
A_zF: .13465
A_zB: .13465

# Moment arm lengths
# how to read:
# dz_xT = distance along z axis to center of top slice viewed in the x direction
dz_xT: -.05656
dz_xB: .05313
dy_xR: .117405
dy_xL: -.117405

dz_yT: -.05656
dz_yB: .05313
dx_yF: .117405
dx_yBa: -.117405

dy_zL: -.12177
dy_zR: .12066
dx_zF: .12066
dx_zB: -.1217
